name: sentinel2
channels:
  - conda-forge
dependencies:
  # ------------------
  # Core
  # ------------------
  - python=3.10
  - pip

  # ------------------
  # Scientific stack
  # ------------------
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - joblib

  # ------------------
  # Geospatial stack (conda-first always)
  # ------------------
  - gdal
  - rasterio
  - geopandas
  - shapely
  - fiona
  - pyproj
  - rtree
  - xarray
  - rioxarray
  - netcdf4

  - dask
  - distributed

  # ------------------
  # Remote sensing / IO
  # ------------------
  - pystac
  - pystac-client
  - requests
  - tqdm

  # ------------------
  # Jupyter / Notebook
  # ------------------
  - notebook
  - nbclassic
  - jupytext
  - ipykernel

  # ------------------
  # Pip-only packages
  # ------------------
  - pip:
      - planetary-computer
      - opencv-python
      - osmnx
      - scikit-image
      - bottleneck